#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart application
setxkbmap -layout us,ru -option grp:alt_shift_toggle,lv3:ralt_switch,misc:typo &
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
polybar &
alacritty &
